server:
  port: 11121
app:
  name: ${spring.application.name}

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yishu?characterEncoding=utf-8&useSSL=false&serverTimezone=Hongkong
    username: root
    password: 123456